### PR TITLE
Updating to 8.4.3

### PR DESCRIPTION
**Pull request by Raihamm**
One last change for updating

### CODE REVIEW

**Comment by jmnorma** [comment]
Can you provide a comment within the PR as to why we're removing this function?

**Comment by Raihamm** [comment]
This function causes an error in deakoTs and is from older gleap versions. Gleap version 8.4.3 works without and doesn't require it.

**Comment by jmnorma** [comment]
> Can you provide a comment within the PR as to why we're removing this function?

@Raihamm What are the errors that you are receiving? Have we done anything to update the way we build android? This previously worked with past releases so I'm curious as to what has changed :)

**Comment by Raihamm** [comment]
Related to https://github.com/DeakoLights/ReactNative-SDK/pull/1/files as to why we are removing this function

**Pull request merged**
